// <auto-generated />
namespace ppRadWeek62.Migration.AuthenticationMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addStudentID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStudentID));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191015245_addStudentID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
